config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios
 
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  #encapsulates all popular routes apps use. in terminal run rake routes to see 
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#added root route

app/models/blog.rb
class Blog < ApplicationRecord
  #this acts like a flag yes or no sets all kind of optons https://api.rubyonrails.org/v5.2.1/classes/ActiveRecord/Enum.html
  enum status:{draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
#data validations
  validates_presence_of :title, :body

  #letting blogs know it belongs to topic
 # belongs_to :topic 
end

app/controllers/blogs_controller.rb
#controller lets you communicate directly from model aka db and views and routes
#basically the traffic cop for all app
class BlogsController < ApplicationController
  #calls these methods before it runs it runs these methods if you are going to have repeatable code best to do a before_action
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  #petergate assign what users can use what the :destroy etc are from controller belo
  #don't want to let user create? put in the except
  access all: [:show, :index], user: {except: [:destroy, :new, :edit, :create, :toggle_status]}, site_admin: :all
  # GET /blogs
  # GET /blogs.json
  #on page load could do blog.limit(1) => only bring one back
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "Blogs"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  #change tab title 
  def show
    @page_title = @blog.title
  end

  # GET /blogs/new
  #does not actually create a new blog no parameters 
  def new
    @blog = Blog.new
    @page_title = "New Post"
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  # this is making new blog or 'C' of Crud notice it takes in params then performs validation
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      #if blog is valid
      if @blog.save
        #redirect_to @blog rails knows this means to show method
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        #dont need this to get up and running its for api
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #see db migrate add to post for this info
  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post status updated"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #set params
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
    <div class="blog-post">
            <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
            <!--Rails Date method takes two args. and calculates the time difference this is a view helper method -->
            <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
            <!--only admin can see if logged in-->
            <% if logged_in?(:site_admin)%>
              <p class="blog-post-meta"><%= link_to blog.status, toggle_status_blog_path(blog) %> -
              <%= link_to 'Edit', edit_blog_path(blog) if logged_in?(:site_admin)%> -
              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }%>
            </p>
            <%end%>
             <p><%= blog.body %></p>
            
            
       
      </div>
 

        
        
        

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-9">
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

 
  <div class="form-group area">
    <%= form.label :body %>
    <%= form.text_area :body, rows:'15',  class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Log", class:"btn btn-primary form-control" %>
  </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="blog-post">
    <h3>Edit blog</h3>
                <%= render 'form', blog: @blog %>
                <%= link_to 'Back', blogs_path %>
</div>
</div>

app/views/blogs/index.html.erb
<%= render @blogs %>

         <%= paginate @blogs %>
</div> <!--error without this div in show and index sidebar no working-->
        


<br>

app/views/blogs/new.html.erb
<div class="blog-post">
            <h2 class="blog-post-title"New Title</h2>
<%= render 'form', blog: @blog %>
<!--<%= link_to 'Back', blogs_path %>--> 
</div>
</div>

app/views/blogs/show.html.erb
<div class="blog-post">
            <h2 class="blog-post-title"><%= @blog.title %></h2>
              <%= link_to 'Edit', edit_blog_path(@blog)  if logged_in?(:site_admin) %> 
                <p class="blog-post-meta"> <%= @blog.body %></p>

<%= link_to 'Back', blogs_path %>
</div>
</div>