config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios
 
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  #encapsulates all popular routes apps use. in terminal run rake routes to see 
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#added root route

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies,  dependent: :nullify
    #5
    accepts_nested_attributes_for :technologies, 
                                   reject_if: lambda { |x| x['name'].blank? }
    #4
    include Placeholder
    validates_presence_of :title, :body, :main_image, :second_image
    mount_uploader :second_image, PortfolioUploader
    mount_uploader :main_image, PortfolioUploader
    #1
    def self.sql
        where(subtitle: "SQL")
    end
#2
    scope :ruby_on_rails, -> {where(subtitle: "Ruby")}

#3
    after_initialize :set_defaults 

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: 350, width: 150)
        self.second_image ||= Placeholder.image_generator(height: 100, width: 50)
    end
    #order postion of portfolios
    def self.by_position
        order("position ASC")
    end    
end

#1-Scope here we are setting what to return now go to controller and def index @port_items = Portfolio.sql will render only items with subtitle = SQL 
#2-Second way to scope

#3-Second way to set default values -first is in the schema like an Enum  
#this only happens at the create and is setting the values of the images
# ||= is a short hand way of doing the below
#     if self.main_image == nil
#         self.main_image = "https://via.placeholder.com/330x150"

# Without ||= the after_initialize would override any values so if you 
# are asking for a url to a picture and user provides it and you dont 
# use ||= then after_initialize would override with the values provided need a savepoint
#4. from the concern files allows us to copy over the url and pass the height and width
#5. allows us to create single portfolio item and slide in multiple technologies 
# reject_if: lambda is code for validation so it wont allow it to save with out a technologies name
# you can add multiple validations here, however, since we only have the name set up on technologies table thats all I can reject

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  access all: [:show, :index], user: {except: [:destroy, :new, :edit, :create, :sort]}, site_admin: :all
  #here you can limit what returns like Portfolio.all or Portfolio.where(subtitle: "SQL")
    def index
        @port_items = Portfolio.by_position
        @page_title = "Portfolio Projects"
    end
#note here we have typo on the second value
    def sort
      params[:order].each do |key, value|
        Portfolio.find(value[:id]).update(position: value[:postion])
      end
  
      #render :nothing => true
    end
        #only renders does not create!
    def new
        @port_items = Portfolio.new
        3.times {@port_items.technologies.build}
    end

    def create                     #from private at the bottom
        @port_items = Portfolio.new(portfolio_params)
    
        respond_to do |format|
          #if blog is valid
          if @port_items.save
            #redirect_to portfolio main page. use rake routes to see where you can send
            format.html { redirect_to portfolios_path, notice: 'Your Portfolio was successfully created.' }
            #dont need this to get up and running its for api
            #format.json { render :show, status: :created, location: @blog }
          else
            format.html { render :new }
            Eformat.json { render json: @blog.errors, status: :unprocessable_entity }
          end
        end
    end

    def edit
        #tell it what one to look up based on URI like portfolio/1/edit - the 1 is the id 
        @port_items = Portfolio.find(params[:id])
        
    end
    def update
                                     #from below private       
        @port_items = Portfolio.find(params[:id])
        
        respond_to do |format|
          if @port_items.update(portfolio_params)
            format.html { redirect_to portfolios_path, notice: 'Portoflio was successfully updated.' }
            #format.json { render :show, status: :ok, location: @blog }
          else
            format.html { render :edit }
            #format.json { render json: @blog.errors, status: :unprocessable_entity }
          end
        end
      end

    def show
        @port_items = Portfolio.find(params[:id]) 
        @page_title = @port_items.title 
    end
    def destroy
        #perform look up on id
        @port_items = Portfolio.find(params[:id]) 
        #destroy record
        @port_items.destroy
        #redirect after destroying 
        respond_to do |format|
          format.html { redirect_to portfolios_url, notice: 'Recorded was removed' }
          
        end
      end

#Want to add a new Item to the page have to add it below      
      private 
      def portfolio_params
        params.require(:portfolio).permit(:title, 
                                          :subtitle, 
                                          :body,
                                          :main_image,
                                          :second_image, 
                                          technologies_attributes: [:name]
                                          )
      end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @port_items, local: true) do |form| %>
 
<div class="row">
  <div class="col-md-5">
      <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: "form-control" %>
    </div>
  

    <div class="form-group">
      <%= form.file_field :main_image %>
    </div>

    <div class="form-group">
     <%= form.file_field :second_image %>
    </div> 
  </div>   
  <div class="col-md-7">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: "form-control", rows: 13 %>
    </div>
  </div>
</div>

<div class="col-md-8">
  <h2>Technologies Used:</h2>
  <div>                <!--this mapped from portfolios.rb-->
    <%=form.fields_for :technologies do |t|%>
    <div class="form-group">
    <%= t.label :name%>
    <%= t.text_field :name, class: "form-control"%>
    </div>
    <%end%>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary form-control" %>
  </div>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb




<h1>lined up </h1>
<!--Rails way to create a path to another page-->
<%=link_to "Create a New Item", new_portfolio_path  if logged_in?(:site_admin)%>

<% @port_items do |x| %>
    <p><%= link_to x.title, portfolio_path(x)%></p>
    <p><%=x.subtitle%></p>
    <p><%=x.body%></p>
    <!--run this unless the image is nil --> 
    <%= image_tag x.second_image unless x.second_image.nil? %>
    <!--Pass into the path the id from the iteration-->
    <%=link_to "Edit", edit_portfolio_path(x)  if logged_in?(:site_admin)%>
    <!--Without the method: :delete it would think it is the show page notice the paths are the same-->
    <%= link_to 'Delete Item', portfolio_path(x), method: :delete, data: { confirm: 'Are you sure?' }  if logged_in?(:site_admin)%>
<%end%>


app/views/portfolios/edit.html.erb
<div class="container port_n_e">
<h1>Edit this Portofolio Item</h1>

<%= render "form", port_items:  @port_items%>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
        <div class="container">
<%=link_to "Create a New Item", new_portfolio_path  if logged_in?(:site_admin)%>
          <div class="row sortable">
          <% @port_items.each do |x| %>
            <div class="col-md-4 <%= "move" if logged_in?(:site_admin)%>" data-id='<%=x.id%>' >
              <div class="card mb-4 shadow-sm">
              
                <%= image_tag x.main_image.url, width:'100%' unless x.second_image.nil? %>
                <div class="card-body" >
                  <p class="card-text"><span class ='portTitle'><%= link_to x.title, portfolio_path(x)%></span>
                  <span class="subTitle"><%=x.subtitle%></span>
                  </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'Delete Item', portfolio_path(x), method: :delete, data: { confirm: 'Are you sure?' }  if logged_in?(:site_admin)%>
                      <%=link_to "Edit", edit_portfolio_path(x)  if logged_in?(:site_admin)%>
                    </div>
                    
                  </div>
                </div>
              </div>
          
            </div>
            <%end%>
  </div>
    
</div>


<!--Rails way to create a path to another page-->

app/views/portfolios/new.html.erb
<div class="container port_n_e">
    <h1>Create a new Portfolio Item</h1>

    <%= render "form",  port_items:  @port_items%>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
    <div class="row">
        <div class="col-md-7">
        <%= image_tag @port_items.main_image.url, width: '100%'%>
        </div>
        <div class="col-md-5">
            <h1><%=@port_items.title%><h1>
            <hr>
            <h4><i><%=@port_items.subtitle%></i></h4>
            <p><%=@port_items.body%></p>
            <h3>Technologies Used</h3>
<!--Get just the technologies values-->
            <% @port_items.technologies.each do |t|%>
             <p> <em> <%= t.name %></em></p>
            <% end %>
        </div>
    </div>
</div>






 