config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios
 
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  #encapsulates all popular routes apps use. in terminal run rake routes to see 
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#added root route

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
        <div class="inner">
          <p class='app-footer'><%=@copyright%></p>
        </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">AJ Hephner</h3>
          <nav class="nav nav-masthead justify-content-center">
            <%= nav_helper 'nav-link tags', 'span'%>
            <%= login_helper 'nav-link'%>
           
          </nav>
        </div>
</header>

app/views/shared/_blog_footer.html.erb
    <footer class="blog-footer">
      <p><p><%=@copyright%></p></p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

app/views/shared/_blog_header.html.erb
<div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="#">Large</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
          </div>
        </div>
      </header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex nav-masthead">
            <%= nav_helper 'nav-link', 'span'%>
            <%= login_helper 'nav-link'%> 
            <h4 class='header'>AJ Hephner:</h4><p id='rb'><i>Thoughts if any...</i></p>
            
        </nav>
      </div>

            

app/views/shared/_blog_sidebar.html.erb

<aside class="col-md-4 blog-sidebar">
          <div class="p-3 mb-3 bg-light rounded">
            <h4 class="font-italic">About</h4>
            <p class="mb-0">Items or other information vital to the house</p>
          </div>

          <!--<div class="p-3">
            <h4 class="font-italic">Archives</h4>
            <ol class="list-unstyled mb-0">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>--> 
          <div class="p-3">
            <h4 class="font-italic">Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href='https://www.linkedin.com/in/aj-hephner-25943a6b/'<%=fa_icon "linkedin"%></a></i></li>
            </ol>
          </div>
        </aside>

app/views/shared/_nav.html.erb
   <div class="<%= location %>">
      <%= nav_helper 'none', 'span'%>
    </div>

app/views/shared/_port_mast_head.html.erb
<section class="jumbotron text-center">
<div class="container">
    <h1 class="jumbotron-heading">My Portfolios</h1>
    <p class="lead text-muted">A short sample of some projects I have worked on or created. Github repos are works in progress!</p>
    <p>
    <%=  link_to link_to "Resume", pages_about_path, class: " btn btn-primary my-2"%>
    <%=  link_to link_to "Blogs", blogs_path, class: " btn btn-secondary my-2"%>
    </p>
</div>
</section>

app/views/shared/_port_nav.html.erb
 <header>
  <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Some sample apps and repos of work. These are mostly side projects as I spend a good amount of my time working as a data anaylst and do not share SQL or Salesforce projects</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4"> 
              <h4 class="text-white">Checkout</h4>
              <ul class="list-unstyled">
                <%= nav_helper 'text-white', 'li' %>
                <li><%= login_helper "text-white"%></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Portfolio</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <%= link_to "Back to all items", portfolios_path%>
          <a href="#">Back to top</a>
        </p>
        <p><%=@copyright%></p>
      </div>
    </footer>