config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios
 
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  #encapsulates all popular routes apps use. in terminal run rake routes to see 
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#added root route

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%=@page_title%></title>
    <%= csrf_meta_tags %>
    <meta name="keywords" content= "<%= @seo_keywords %>"/>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <%= video_tag(
        'Aloha-Mundo.mp4',
        id: 'background', 
        autoplay: true,
        loop: true,
        muted: true,
        poster: 'video.png'
       
      )%>
        <%=render "shared/application_nav"%>
          
          <%= yield %>
          <%=render "shared/application_footer"%>
          <%=source_helper%>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%=@page_title%></title>
    <%= csrf_meta_tags %>
    <meta name="keywords" content= "<%= @seo_keywords %>"/>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
         <!--navbar-->
         <%=render 'shared/blog_nav'%>
<!--nav end-->
          
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h3 class="pb-3 mb-4 font-italic border-bottom">My blogs</h3>
            <!--new blog-->  
            <%= link_to 'Create New Blog', new_blog_path  if logged_in?(:site_admin) %>
            
            <%= yield %>
    <!--sidedbar-->
            <%=render 'shared/blog_sidebar'%>
      </div><!-- /.row -->
   
    </main><!-- /.container -->

    <%= render 'shared/blog_footer'%>
    
   </div> 
  </body>
</html>

app/views/layouts/portfolios.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%=@page_title%></title>
    <%= csrf_meta_tags %>
    <meta name="keywords" content= "<%= @seo_keywords %>"/>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class='container'>
  
  <%= render "shared/port_nav"%>
  <!--figure out logged as admin dont show below-->
  <%= render "shared/port_mast_head" unless logged_in?(:site_admin)%>
    <main role="main">
     
          
        <%= yield %>
        <!--FOOTER-->
         <%=render "shared/portfolio_footer"%>
            <%=source_helper%>
    </main>
    </div>
  </body>
</html>